### ISSUE TITLE
Not sufficient documentation

### ISSUE THREAD

**Issue by deep5050** [andreztz/pyradios#29]
This project needs a proper documentation.
a wiki would be great. 

I didn't know about station_by_id() untill i came accross your test files 🙃.

anyway great work.

**Comment by andreztz** [comment]
You can get some documentation through the `help()` command.

```
>>> from pyradios import RadioBrowser
>>> help(RadioBrowser)
```

As soon as possible I will improve the documentation, feel free to suggest new improvements. Thanks.
