### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Axel-Erfurt** [andreztz/pyradios#3]
I just want to thank you for making pyradios.
I've created a GUI using PyQt5 to show the results and save it as txt or m3u.

https://github.com/Axel-Erfurt/getRadioList

![Alt text](https://raw.githubusercontent.com/Axel-Erfurt/getRadioList/master/screenshot.png)

**Comment by webredraptors** [comment]
Wanted to pipe in and also say thanks for this. Makes my life a whole lot easier.
