### ISSUE TITLE
Any call to discover stations by country or state name?

### ISSUE THREAD

**Issue by deep5050** [andreztz/pyradios#30]
It will be great if there is a way to discover stations by country name or state name!

or is there already?

**Comment by andreztz** [comment]
Yes it is possible, first you must get the list of country/state available 

```
>>> from pyradios import RadioBrowser
>>> rb = RadioBrowser()
>>> rb.states()
>>> rb.countries()
>>> rb.countrycodes()
```

So to get the list of radio stations we have the following methods

```
>>> rb.stations_by_state('kolkata')
>>> rb.stations_by_countrycode('IN')
```
