### ISSUE TITLE
feature-suggestion -- adding facet-browser like features

### ISSUE THREAD

**Issue by marc-portier** [andreztz/pyradios#32]
idea is to have the ```search()```  wrapped from a context ```facets()``` that also quantifies the resultset along the various facets: ``` codecs, countries, tags, ... ````

with it one would be able to:

```
fb = rb.facets(**kwargs) 
fb.result     # yielding the equivalent of rb.search(**kwargs)
fb.filter       # remembering the **kwargs used to filter
fb.tags       # yielding a similar list({"name": "..", "stationcount": ".."}) as rb.tags() but narrowed to the tags still in this resultset
fb.coutries #  similarly so, as well as for languages, codecs, tags, ...

fb2 = fb.add(tag="extra filter tag", country="be")    # an more constrained similar response object
fb3 = fb.remove("tag", "language")                    # a less constrained one, removing he passed filter-items
```

open for extra suggestions, and willing to throw in the PR if you are willing to consider this as useful addition

**Comment by marc-portier** [comment]
if people want to comment on this --> here is an implementation

https://github.com/andreztz/pyradios/compare/master...marc-portier:issue/32

**Comment by andreztz** [comment]
@marc-portier This is interesting, I definitely want to add this. Go ahead.
