### ISSUE TITLE
RadioBrowser's init does not handle a socket.herror

### ISSUE THREAD

**Issue by emankced** [andreztz/pyradios#48]
After updating pyradios from 0.0.22 to 1.0.1 I am no longer able to import RadioBrowser because a `socket.herror` (`"Resolver Error 0 (no error)"`) is not handled but passed through. Downgrading pyradios back to 0.0.22 resolved this issue for me. I could reproduce this exception in the same way on my Raspberry Pi. I also tried different DNS servers but the reverse DNS of one of the `all.api.radio-browser.info` IPs is not properly resolved. More to that in **Additional Information**. Anyway, an import line shouldn't throw a network exception.

**How to reproduce**
1. Create a new virtualenv.
2. Install pyradios via pip.
3. Open an interactive python shell.
4. Try to import RadioBrowser: `from pyradios import RadioBrowser`
5. `socket.herror` is raised.

**Affected versions**
 - pyradios 1.0.0
 - pyradios 1.0.1

**Expected behavior**
The exception is properly handled so a program importing RadioBrowser does crash at an import line.

**Log**
```
Network failure
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.10/site-packages/pyradios/base_url.py", line 86, in pick_base_url
    names = fetch_hosts()
  File "/tmp/venv/lib/python3.10/site-packages/pyradios/base_url.py", line 75, in fetch_hosts
    name = rdns_lookup(ip)
  File "/tmp/venv/lib/python3.10/site-packages/pyradios/base_url.py", line 55, in rdns_lookup
    name = socket.gethostbyaddr(ip)
socket.herror: [Errno 0] Resolver Error 0 (no error)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.10/site-packages/pyradios/__init__.py", line 3, in <module>
    from pyradios.radios import RadioBrowser
  File "/tmp/venv/lib/python3.10/site-packages/pyradios/radios.py", line 29, in <module>
    class RadioBrowser:
  File "/tmp/venv/lib/python3.10/site-packages/pyradios/radios.py", line 60, in RadioBrowser
    base_url = pick_base_url()
  File "/tmp/venv/lib/python3.10/site-packages/pyradios/base_url.py", line 86, in pick_base_url
    names = fetch_hosts()
  File "/tmp/venv/lib/python3.10/site-packages/pyradios/base_url.py", line 75, in fetch_hosts
    name = rdns_lookup(ip)
  File "/tmp/venv/lib/python3.10/site-packages/pyradios/base_url.py", line 55, in rdns_lookup
    name = socket.gethostbyaddr(ip)
socket.herror: [Errno 0] Resolver Error 0 (no error)
```

**Desktop**
 - OS: Fedora Workstation 35
 - DNS resolver: systemd-resolved

---

 - OS: Raspberry Pi OS bullseye
 - DNS resolver: dnsmasq

**Additional Information**
I'm able to resolve `all.api.radio-browser.info` fine:
```
$ host all.api.radio-browser.info
all.api.radio-browser.info has address 91.132.145.114
all.api.radio-browser.info has address 45.77.62.161
all.api.radio-browser.info has address 95.179.139.106
all.api.radio-browser.info has IPv6 address 2a03:4000:37:42:c4fe:4cff:fea7:8941
all.api.radio-browser.info has IPv6 address 2001:19f0:6801:19d7:5400:2ff:fe71:bdb7
all.api.radio-browser.info has IPv6 address 2001:19f0:5001:32a4:5400:2ff:fe37:75c2
```

But I'm not able to resolve the reverse DNS of `45.77.62.161`:
```
$ host 45.77.62.161
Host 161.62.77.45.in-addr.arpa not found: 2(SERVFAIL)
```

Expected is something more like this:
```
$ host 91.132.145.114
114.145.132.91.in-addr.arpa domain name pointer de1.api.radio-browser.info.
```

---

Also on my Raspberry Pi the exact error string is `"Host name lookup failure"`.

---

Botamusique, a Mumble music bot, uses pyradios and is crashing with the current pyradios version on my machines. I already created an issue there the other day: https://github.com/azlux/botamusique/issues/306

**Comment by andreztz** [comment]
@emankced moving this line https://github.com/andreztz/pyradios/blob/3565993cdfd305ceb9cb0c40df01cf78547f8ecb/pyradios/radios.py#L60 to the `__init__` method should solve the import problem. I will fix it as soon as possible. Feel free to suggest improvements.

**Comment by emankced** [comment]
@andreztz Thank you, that patch did it ツ
