### ISSUE TITLE
countries() wrong implementation

### ISSUE THREAD

**Issue by PeterBremer-Ph** [andreztz/pyradios#54]
countries() according https://de1.api.radio-browser.info/#List_of_countries 
should call json/countries/
not the deprecated json/countrycodes
There is a huge difference between the two, the json/countries/ also includes the names of the country, not only the code.
To be changed in lines 88 and 92 of radios.py in \Lib\site-packages\pyradios

**Comment by andreztz** [comment]
@PeterBremer-Ph What version are you running? The main branch, if I'm not mistaken, is all okay.

https://github.com/andreztz/pyradios/blob/master/pyradios/radios.py#L88-L92

    def countries(self, code=None):

**Comment by andreztz** [comment]
@PeterBremer-Ph What version are you running? The main branch, if I'm not mistaken, is all okay

https://github.com/andreztz/pyradios/blob/7627b20bde8aa412deac79c77eab1babee9d8a61/pyradios/radios.py#L72=L92

**Comment by PeterBremer-Ph** [comment]
Strange.
I just used pip install. It installed 1.0.1.dist
That is also what I think I see at https://github.com/andreztz/pyradios/blob/7627b20bde8aa412deac79c77eab1babee9d8a61/pyradios/__init__.py
and also in my installed version.

**Comment by andreztz** [comment]
@PeterBremer-Ph Sorry, I am mistaken. Version 1.0.1 has this error. I have just released version 1.0.2 with the fixes.

**Comment by PeterBremer-Ph** [comment]
Upgraded to 1.0.2, issue solved. Thanks.
