### ISSUE TITLE
Enable continuous integration

### ISSUE THREAD

**Issue by scls19fr** [andreztz/pyradios#8]
Hello,

you should consider setting a continuous integration server (travis-ci.com or Github Action).
By enabling CI, it will be possible to run automatically unit tests (using `pytest` for example), ensure that code respect PEP8 (using `flake8` for example)

Kind regards

**Comment by andreztz** [comment]
I will add a standard model provided by github, feel free to suggest improvements, thanks.

**Comment by scls19fr** [comment]
It seems to be a good starting.
